### ISSUE TITLE
undefined local variable or method "event"

### ISSUE THREAD

**Issue by consulthys** [logstash-plugins/logstash-output-stomp#13]
I've introduced a bug in my [last PR](https://github.com/logstash-plugins/logstash-output-stomp/pull/9) due to a bad merge on my local branches.

```
NameError: undefined local variable or method `event' for #<LogStash::Outputs::Stomp:0xaf2d433>
         multi_receive at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-output-stomp-2.0.5/lib/logstash/outputs/stomp.rb:78
                  each at org/jruby/RubyHash.java:1342
         multi_receive at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-output-stomp-2.0.5/lib/logstash/outputs/stomp.rb:77
  worker_multi_receive at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:130
         multi_receive at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:114
          output_batch at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301
                  each at org/jruby/RubyHash.java:1342
          output_batch at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301
           worker_loop at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:232
         start_workers at /usr/local/Cellar/logstash/2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:201
```

**Comment by consulthys** [comment]
@ph is there any chance to get this one merged? Thanks much

**Comment by ph** [comment]
Thanks for the ping @consulthys  really appreciated! I've merged the PR and published 3.0.3 that contains your changes!

**Comment by consulthys** [comment]
Awesome, thank you @ph !!
